name: flutter_persistent_queue
description: >
  Simple file-based non-volatile persistent queue implementation for flutter.
  Ideal for in-device sequential buffers that must persist between app runs.
version: 6.2.0+1
homepage: https://github.com/oakromulo/flutter_persistent_queue
repository: https://github.com/oakromulo/flutter_persistent_queue.git
issue_tracker: https://github.com/oakromulo/flutter_persistent_queue/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  localstorage: #^4.0.0+1
    git:
      url: https://github.com/kee-org/flutter_localstorage
      ref: a47a2457b481ee779da4201ceb63d3436e71d053

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
